### PR TITLE
(Progress)  Module 10: Sequential Combinational Multiplier with ready-valid interface

### PR DESCRIPTION
**Pull request by SalmanOFC**
Completed Lab 1,2,3,4
Readme.md files completed for Lab 1 and 2 and are underway for Lab 3 and Lab 4.
Comments added inside each code.
The forked repository is up to date and re-based with the main repository.

### CODE REVIEW

**Comment by SalmanOFC** [comment]
Pending documentation
Pending makefiles
Pending some C files in assembly lab

**Comment by SalmanOFC** [comment]
Updated

- Added ready-valid interface
- Edited documentation

**Comment by shehzmak** [comment]
Why are all your files in Fazail's folder?

**Review by shehzmak — CHANGES_REQUESTED** [review]

**Comment by SalmanOFC** [comment]
> Why are all your files in Fazail's folder?

No mam, my files are in "Salman/assignments" folder. The files in Fazail folder are the files that I rebased into my git repository.

**Comment by SalmanOFC** [comment]
I will be resolving this issue and creating another pull request to make sure everything is fixed.

**Pull request closed without merging**
